dist: xenial
language: python
python:
- '3.5'
install:
- pip install tox
script: tox
deploy:
  provider: pypi
  user: n1te
  password:
    secure: "TbwRg1JgbncLvYTj4NSoNuF+jGXsEZfljYqiOQX/lvW8sv8GRwdU85SW4qQRxlv/ABwwDG7g6u5iEcy/5aby/+fKD5QmtdSbT6uT6qMZQPVl80tTjZldDwJgqDxK7cDjA/hFqmvAg2TYH0hR9Pc8qWi6ZttPz8J5VlYMLJaZbzAME16axTEiQOLMf65GruxFKTU9xwFpfNVzqTIvX9bzNJidmFmvaDvYvlrNyS1ScbngtiSkoaVt/4Q8hmetEArTl9OT/nGafA0CC9VEombKitLzKk+w09J6zxwl0Z4LF7+pmGXblts5GMVHDb8UWdgCv/EqXNj0Iu1txlHcL2Du25HQyMp8d9lrctaPJMdLQq1nvl03Zrx4QV6ADTdWxyXHTwir2SVJg7xPCMyL8/nE4u6QTnfhkg4SSXY9EberGruaHuu7nvEYJcoqQt/U3bpDni6CA2IIkfYieEOj9UOzL/0T40pJYDuiLgPWaHSMDOG+2ywdYHsFmc4z6Z4iyTKXtpwwCezbdt6LPwondYabv9eU5sYgIPeOqXNcFRwzL67Pkqj76+TkLB9+XX+xfHdUxtqVT2ttwSp3ddFBMh45x8+d+4w/96Toco0Cdu44FqjpKmKCgR0oqCjlQRshe49vHFhLW44II7wxDPAT/1oZo12BFJ2oSNSlVxZBSFoScNA="
